In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

TO GET SPECIFIC ELEMENTS FROM THE ARRAY WE USE SLICING 

arr[1:8] REMEMBER HERE 1 IS INCLUDED BUT 8 IS EXCLUDED

In [5]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

IF WE WANT FROM STARTING ELEMENT TILL A PARTICULAR ELEMENT 

In [7]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

VICE-VERSA IF WE WANT ELEMENTS FROM A PARTICULAR INDEX TILL END THEN 

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

BROADCASTING

WHEN WE CALL OUT A SUB SECTION OF AN ARRAY AN ASSIGN IT TO A NEW VARIABLE, A NEW ARRAY IS NOT CREATED RATHER IT IS A VIEW OF THE ORIGINAL ARRAY

IF WE MODIFIED THE NEW VARIABLE THE CHANGES WOULD ALSO BE VISIBLE IN THE ORIGINAL ARRAY


In [9]:
arr[0:5]=100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)

In [12]:
slice_of_arr=arr[0:4]

In [13]:
slice_of_arr

array([0, 1, 2, 3])

In [14]:
slice_of_arr[0:]=737

In [15]:
slice_of_arr

array([737, 737, 737, 737])

In [16]:
arr

array([737, 737, 737, 737,   4,   5,   6,   7,   8,   9,  10])

TO OVERCOME THIS PROBLEM WE USE .copy METHOD TO CREATE A COPY OF THE ORIGINAL ARRAY AND THEN USE IT

In [17]:
arr_copied=arr.copy()

In [18]:
arr_copied[:]=1

In [19]:
arr_copied

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
arr

array([737, 737, 737, 737,   4,   5,   6,   7,   8,   9,  10])

INDEXING WITH 2D ARRAYS

In [21]:
arr_2d=np.array([[11,22,33],[44,55,66],[77,88,99]])

In [22]:
arr_2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

RETRIEVING DATA USING DOUBLE BRACKET NOTATION

In [23]:
arr_2d[0][2]

33

RETRIEVING DATA USING SINGLE BRACKET NOTATION

In [24]:
arr_2d[1,2]

66

RETRIEVING MULTIPLE ELEMENTS

FIRST CREATE A STRUCTURE FOR ROWS AND COULMNS

In [25]:
arr_2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [26]:
arr_2d[1:,:2]

array([[44, 55],
       [77, 88]])

In [27]:
arr_2d[:2,:2]

array([[11, 22],
       [44, 55]])

In [28]:
arr_2d[:,1]

array([22, 55, 88])

CONDITIONAL INDEXING

In [30]:
arr_bool_check=np.arange(0,11)

In [31]:
arr_bool_check

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

IF WE GIVE A CONDITION TO THE ARRAY THEN THE ELEMENTS THAT SATISFY THAT CONDITION RETURN True AND REMAINING False

In [32]:
arr_bool_check > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

WE CAN SAVE THIS RETURNED ARRAY INTO A NEW VARIABLE


In [34]:
arr_bool_returned=arr_bool_check >5

In [35]:
arr_bool_returned

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

NOW IF WANT THE ELEMENTS THAT SATISFY THE CONDITION ONLY THEN WE WILL USE 

In [36]:
arr_bool_check[arr_bool_returned]

array([ 6,  7,  8,  9, 10])

OR ELSE IF WE WANT TO COMPACT IT FURTHER WE WILL DO THIS

In [37]:
arr_bool_check[arr_bool_check >5]

array([ 6,  7,  8,  9, 10])

PRACTISE


In [38]:
arr_2d=np.arange(50).reshape(5,10)

In [39]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
arr_2d[1:4,5:8]

array([[15, 16, 17],
       [25, 26, 27],
       [35, 36, 37]])