NUMPY 

NUMPY COMES IN TWO FLAVOURS VECTORS AND MULTI DIMENSIONAL MATRICES.

In [2]:
my_list=[1,2,3,4]

In [3]:
import numpy as np


WE USE np.array() METHOD TO CONVERT A LIST INTO ARRAY FORM.

In [4]:
np.array(my_list)

array([1, 2, 3, 4])

TO SAVE THE FORMATTED ARRAY WE ASSIGN IT TO A VARIABLE.

In [5]:
my_arr=np.array(my_list)

In [6]:
my_arr 

array([1, 2, 3, 4])

FOR CREATING MULTIDIMENSIONAL ARRAY FROM A LIST WE APPLY THE SAME PROCEDURE

In [7]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_multi_arr= np.array(my_list)

In [9]:
my_multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

TO GET A 1D MATRIX FOR A RANGE IN INTEGERS WE USE np.arange() FUNCTION WHERE WE GIVE THE LOWER BOUND AND UPPER BOUND

THE LOWER BOUND IS INCLUDED AND THE UPPER BOUND IS EXCLUDED

In [10]:
ranged_arr=np.arange(2,10)

In [11]:
ranged_arr

array([2, 3, 4, 5, 6, 7, 8, 9])

NOW IF WE WANT THE ELEMENTS TO BE IN A.P WE ADD THE COMMON DIFFERENCE IN THE np.arange() FUNCTION 

In [12]:
stepped_arr=np.arange(3,27,3)

In [13]:
stepped_arr

array([ 3,  6,  9, 12, 15, 18, 21, 24])

FOR CREATING A MATRIX THAT HAS ALL THE ELEMENTS AS ZERO WE USE np.zeros() FUNCTION

In [14]:
zero_matrix=np.zeros(5)

In [15]:
zero_matrix

array([0., 0., 0., 0., 0.])

IF WE WANT THE ZERO MATRIX TO BE MULTIDIMENSIONAL THEN WE GIVE MORE PARAMETERS IN THE "TUPLE-FORMAT" TO  np.zeros() FUNCTION

In [16]:
multiD_zero_matrix=np.zeros((2,3,4))

In [17]:
multiD_zero_matrix

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

SIMILARILY IF WE WANT THE MATRIX TO HAVE ALL THE ELEMENTS AS ONE THEN WE USE np.ones() FUNCTION

In [18]:
one_matrix=np.ones(5)

In [19]:
one_matrix

array([1., 1., 1., 1., 1.])

SIMILIARILY TO THE ZERO MATRIX IF WE WANT MULTIDIMENSIONAL ARRAY WE PASS THE ALL THE PARAMAETERS IN TUPLE FORMAT TO THE np.ones() FUNCTION

In [20]:
multiD_one_matrix=np.ones((2,3))

In [21]:
multiD_one_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

UNLIKE np.arange() WHICH GIVES PROGRESSIVE STEPS BETWEEN THE GIVEN UPPER AND LOWER BOUNDS, THE np.linsapce() GIVES EQUAL SPACE BETWEEN CONSECUTTVE ELEMENTS.

IN np.linspace() NO OF ELEMENTS WE WANT IS PROVIDED AND IN np.arange() THE DIFFERENCE BETWEEN EACH ELEMENT IS PROVIDED.

ALSO, IN np.linspace() BOTH THE UPPER BOUND AND THE LOWER BOUND ARE INCLUDED

In [22]:
list_with_no_of_ele_provided=np.linspace(2,10,11)

In [23]:
list_with_no_of_ele_provided

array([ 2. ,  2.8,  3.6,  4.4,  5.2,  6. ,  6.8,  7.6,  8.4,  9.2, 10. ])

TO CREATE IDENTITY MATRIX WE USE np.eye()

In [24]:
identity_matrix=np.eye(5)

In [25]:
identity_matrix


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

TO CREATE A MATRIX WITH RANDOM INTEGERS AS THEIR ELEMENTS WE np.random.randint() FUNCTION

np.random.randint() HAS A LOWER BOUND INCLUDED A UPPER BOUND EXCLUDED AND NO OF ELEMENTS IN SEQUENCE

In [26]:
rand_int_matrix=np.random.randint(5,1000,10)

In [27]:
rand_int_matrix

array([710, 188, 988, 591, 620, 637,  14, 584, 928, 650])

IF WE WANT ELEMENTS RANDOMLY FROM 0 TO 1 THEN WE USE np.random.rand() FUNCTION

ALSO NOTE WE DON'T NEED TUPLE FORMAT TO MAKE MULTI-D MATRIX USING THIS FUNCTION

In [28]:
rand_mat_bw_0_1=np.random.rand(11,2)

In [29]:
rand_mat_bw_0_1

array([[0.26412212, 0.2025493 ],
       [0.29919529, 0.88710726],
       [0.19539844, 0.15597291],
       [0.07587784, 0.19143709],
       [0.84517314, 0.29647839],
       [0.63122794, 0.89755757],
       [0.5693783 , 0.77661465],
       [0.84468603, 0.15179858],
       [0.10074045, 0.27186285],
       [0.89944295, 0.16698305],
       [0.3501954 , 0.92099467]])

IF WE WANT TO RETURN SAMPLE SPACES FROM NORMAL OR GUASSIAN DISTRIBUTION THEN WE USE np.random.randn()

WE DON'T NEED TUPLE FORMATING FOR np.random.randn()

In [30]:
sample_ele_matrix=np.random.randn(3,3)

In [31]:
sample_ele_matrix

array([[-0.86011156, -0.18676605,  0.3630026 ],
       [ 1.1939413 , -1.10898174, -1.34343105],
       [-0.50337836, -2.09506243, -1.8962962 ]])

RESHAPING AN ARRAY


In [32]:
to_be_reshaped=np.arange(25)

In [33]:
to_be_reshaped.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

TO FIND THE MAXIMUM ELEMENT IN THE ARRAY WE USE np.max() AND SIMULTANEOUSLY np.min() FOR MINIMUM

In [34]:
sample_ele_matrix.max()

1.1939413043527405

In [35]:
sample_ele_matrix.min()

-2.095062425802124

TO FIND THE INDEX AT WHICH THE MAXIMUM AND MINIMUM ELEMENTS ARE LOCATED WE USE .argmax() AND .argmin() METHODS

In [36]:
sample_ele_matrix.argmax()

3

In [37]:
sample_ele_matrix.argmin()

7

TO FIND THE SHAPE OF AN ARRAY WE USE .shape METHOD

REMEMBER THAT NO PARENTHESIS ARE USED IN .shape METHOD

In [38]:
my_arr.shape

(4,)

TO RESHAPE THE ARRAY WE USE .reshape() METHOD

In [41]:
my_arr=my_arr.reshape(2,2)

In [42]:
my_arr.shape

(2, 2)

TO FIND WHAT KIND OF DATA TYPE IS BEING USED IN THE ARRAYS WE USE .dtype METHOD

REMEMBER NO PARENTHESIS ARE BEING USED

In [43]:
my_arr.dtype

dtype('int32')

INSTEAD OF TYPING np.random.rand() WHAT WE CAN DO IS from numpy.random import rand